Fix #5 - Security Patches. Fixed all npm audit issues.
mikeal/response pull request #12
Opened 2018-06-01 03:46 UTC by micksatana

Security Patches. Fixed all npm audit issues.

[x] Upgrade dependencies.
  - There're changes in how to use mime types and how to lookup types.
[x] `npm test` all passed successfully.

2018-10-03 19:11 UTC, chiendv approved these changes

2018-10-03 20:38 UTC, mikeal requested changes

2018-10-03 20:38 UTC, mikeal commented on .gitignore
> +# Logs
Can we get this file out of the PR. It's a little larger than most standard .gitignore files.

2018-10-03 20:38 UTC, mikeal commented on index.js
> +  , mimeTypes = require('mime-types')
If we're moving to this new module I'd like to see us remove the old one entirely.

2018-10-03 20:38 UTC, mikeal commented on tests/test-location.js
> +        server.listen(8084,function(){
Is there a reason this needed to change? My guess is that you changed this locally to get a test working after a prior one had been left hanging and it ended up in the pull request :)

2018-10-04 17:41 UTC, merged

2018-10-04 17:41 UTC, mikeal commented
Thanks! I made one more adjustment, removing package-lock.json, before merging :)